# Generated by Django 4.1.2 on 2022-11-21 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project_blog',
            new_name='ProjectBlog',
        ),
    ]
