# Generated by Django 4.1.2 on 2022-11-21 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_project_blog_projectblog'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectBlog',
            new_name='Blog',
        ),
    ]
